version: '3'
services:
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${{ secrets.DB_PASS }}
      - POSTGRES_USER=${{ secrets.DB_USER }}
      - POSTGRES_DB=${{ secrets.DB_NAME }}
      - POSGRES_HOST=${{ secrets.DB_HOST }}
  
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: bercanda-app-service
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
volumes:
  data:
