version: '3'
services:
  db:
    image: postgres
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${{ secrets.DB_PASS }}
      - POSTGRES_USER=${{ secrets.DB_USER }}
      - POSTGRES_DB=${{ secrets.DB_NAME }}
      - POSGRES_HOST=${{ secrets.DB_HOST }}
  
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: bercanda-app-service
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_PASSWORD=${{ secrets.DB_PASS }}
      - POSTGRES_USER=${{ secrets.DB_USER }}
      - POSTGRES_DB=${{ secrets.DB_NAME }}
      - POSGRES_HOST=${{ secrets.DB_HOST }}
      - DEBUG=${{ secrets.DEBUG }}
      - DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
    depends_on:
      - db
volumes:
  data:
