name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client
      
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STATIC_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY  }}
          script: |
            sudo docker container rm -f law-tugas01 || true
            sudo docker image rm -f ${{ secrets.REGISTRY_USER }}/${{ secrets.REGISTRY_IMAGE }}:latest || true
            sudo docker run --name law-tugas01 -d -p 8000:8000 ${{ secrets.REGISTRY_USER }}/${{ secrets.REGISTRY_IMAGE }}:latest
