name: Django App Deployment

on:
  push:
    branches:
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set Up Environment Variables
      run: |
        echo "DEBUG=${{ secrets.DEBUG }}" >> .env
        echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env
        cp .env BercandaDotComApp/.env

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get remove containerd.io
          sudo apt-get install -y docker.io
          sudo apt-get install -y docker-compose

      - name: Build and push Docker image
        run: |
          docker build -t bercanda-dot-com-image .
          docker tag revelio-be-image:latest 104.154.120.50/bercanda-dot-com-image:latest
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin 104.154.120.50
          docker push 104.154.120.50/bercanda-dot-com-image:latest

      - name: SSH into VM and deploy
        uses: appleboy/ssh-action@master
        with:
          host: 104.154.120.50
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd .
            docker-compose pull
            docker-compose down
            docker-compose up -d

